version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/quiz_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api_service:3000
      - NEXT_PUBLIC_FEEDBACK_URL=http://feedback_service:3100
    depends_on:
      - api_service
      - feedback_service
    networks:
      - quiznet

  api_service:
    build:
      context: ./backend/api_service
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file: ./backend/api_service/.env
    depends_on:
      - postgres
    networks:
      - quiznet
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:3000/health || curl -f http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  feedback_service:
    env_file: ./backend/feedback_service/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/feedback
    build:
      context: ./backend/feedback_service
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    depends_on:
      - mongo
    networks:
      - quiznet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: quiz_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - quiznet

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    networks:
      - quiznet
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  mongo_data:

networks:
  quiznet:
    driver: bridge

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
