@userId = cmbnkw1ft0000dst7jvqg1ri3

### Get all users
GET http://localhost:3000/v1/users HTTP/1.1

### Get users with pagination
GET http://localhost:3000/v1/users?page=1&limit=5 HTTP/1.1

### Get user by ID
GET http://localhost:3000/v1/users/{{userId}} HTTP/1.1

### Create new user
POST http://localhost:3000/v1/users HTTP/1.1
Content-Type: application/json

{
  "keycloakId": "4028c181-fdd5-48a0-b8a5-3b54b49c7251",
  "email": "alan.doe@example.com",
  "username": "alandoe",
  "firstName": "Alan",
  "lastName": "Doe",
  "avatar": "https://example.com/avatar.jpg"
}

### Update user
PUT http://localhost:3000/v1/users/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "email": ""
}

### Update user - Empty body (should fail)
PUT http://localhost:3000/v1/users/{{userId}} HTTP/1.1
Content-Type: application/json

### Update user - Empty object (should fail)  
PUT http://localhost:3000/v1/users/{{userId}} HTTP/1.1
Content-Type: application/json

{}

### Update user - Invalid field (should fail)
PUT http://localhost:3000/v1/users/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "hello": "world"
}

### Deactivate user
DELETE http://localhost:3000/v1/users/{{userId}} HTTP/1.1

### Get user's quizzes
GET http://localhost:3000/v1/users/{{userId}}/quizzes HTTP/1.1

### Get user's quizzes with pagination
GET http://localhost:3000/v1/users/{{userId}}/quizzes?page=1&limit=5 HTTP/1.1